name: release
on:
  push:
    branches:
      - main
    tags:
      - "v*"

jobs:
  build:
    name: Build release assets
    runs-on: golang:1.16
    steps:
    - uses: actions/checkout@v2

    - name: Set the release version (tag)
      if: startsWith(github.ref, 'refs/tags/v')
      shell: bash
      run: echo "RELEASE_VERSION=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV

    - name: Set the release version (main)
      if: github.ref == 'refs/heads/main'
      shell: bash
      run: echo "RELEASE_VERSION=canary" >> $GITHUB_ENV

    - name: Build release
      run: make build

    - name: Upload artifact
      uses: actions/upload-artifact@v1
      with:
        name: <%= moduleName %>.wasm
        path: ./<%= moduleName %>.wasm
